# Clubhouse Task (#645): 
# Create a Github Action (GHA) to run our tests every time a PR is opened (or a branch is updated within a PR). 
# This is called Continuous Integration (CI) -- the idea being that we are continually testing our code.


# Questions: 
# 1. Which tests should be included? All? 
# 2. Should I run the tests with pytest?
# 3. Should this be based off the notebooks (such as the dataset publishing notebook)? 
# 4. Should I use Flake8? ("uses it to lint all files") <- idk what that means

name: test-workflow

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Globus auth
      run: 'echo "$GLOBUS_CONFIG" > ~/.globus-native-apps.cfg'
      shell: bash
      env:
        GLOBUS_CONFIG: "${{ secrets.GLOBUS_CONFIG }}"
        
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
#        pip install foundry_ml --upgrade
#        pip install mdf_connect_client
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
#        stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    
    - name: Test with pytest
      run: |
        pytest





#     - name: Foundry Instantiation
#       run: python -m from foundry import Foundry                  # ??????????

        
#     - name: idk what im doing
#       run: $F_OBJECT.test_foundry_init_cloud()                    # No way that this is correct
#       env: 
#         F_OBJECT: Foundry()                                       # Same with this... definitely wrong :( 
#         # Should the variable end with "_PATH"? -> https://docs.github.com/en/actions/reference/environment-variables
        
#     - name: Run tests
#       inputs:
#         file-path: # id of input
#           description: Path to test script
#           required: true
#           default: foundry_dataframe.json
#       outputs: 
#         results-file: # id of output
#           description: Path to results file
